---
%{PREFIX}alias:
  - PRIMARY KEY  (alias_id)
  - KEY alias_domain (alias_domain)
  - KEY alias_code (alias_code)
%{PREFIX}approval:
  - PRIMARY KEY  (approval_id)
  - KEY approval_revision_id (approval_id,approval_revision_id,approval_entry_id,approval_blog_id)
%{PREFIX}approval_notification:
  - KEY notification_rev_id (notification_rev_id,notification_entry_id,notification_blog_id,notification_receive_user_id,notification_receive_usergroup_id)
%{PREFIX}blog:
  - PRIMARY KEY  (blog_id,blog_left,blog_right,blog_status,blog_indexing)
  - KEY blog_domain (blog_domain)
  - KEY blog_id (blog_id,blog_status)
%{PREFIX}cache_data:
  - PRIMARY KEY (cache_data_key)
  - KEY cache_key (cache_data_key,cache_data_lifetime)
%{PREFIX}cache_tag:
  - PRIMARY KEY (cache_tag_name,cache_tag_key)
%{PREFIX}cache_reserve:
  - PRIMARY KEY  (cache_reserve_datetime,cache_reserve_entry_id,cache_reserve_blog_id)
  - KEY cache_reserve_datetime (cache_reserve_datetime,cache_reserve_blog_id)
%{PREFIX}category:
  - PRIMARY KEY  (category_id,category_left,category_right,category_status,category_indexing)
  - KEY category_code (category_code,category_left,category_right)
  - KEY category_id (category_id,category_status)
  - KEY category_status (category_status,category_left,category_right,category_blog_id)
%{PREFIX}column:
  - PRIMARY KEY  (column_id)
  - KEY entry_sort (column_entry_id,column_sort)
%{PREFIX}column_rev:
  - PRIMARY KEY  (column_id,column_rev_id)
  - KEY entry_sort (column_entry_id,column_sort,column_rev_id)
  - KEY entry_revision (column_entry_id,column_rev_id)
%{PREFIX}comment:
  - PRIMARY KEY  (comment_entry_id,comment_id,comment_status)
%{PREFIX}config_set:
  - PRIMARY KEY  (config_set_id)
%{PREFIX}config:
  - KEY config_blog_id (config_blog_id,config_sort,config_rule_id,config_module_id,config_set_id)
%{PREFIX}dashboard:
  - KEY dashboard_key (dashboard_key,dashboard_blog_id)
  - KEY dashboard_sort (dashboard_sort,dashboard_blog_id)
%{PREFIX}entry:
  - PRIMARY KEY  (entry_id,entry_start_datetime,entry_end_datetime,entry_status)
  - UNIQUE KEY entry_posted_datetime (entry_posted_datetime,entry_id)
  - KEY entry_code (entry_code,entry_category_id,entry_blog_id,entry_status)
  - KEY entry_status (entry_datetime,entry_start_datetime,entry_end_datetime,entry_status,entry_indexing,entry_id)
  - KEY entry_user_id (entry_user_id)
  - KEY entry_category_id (entry_category_id)
  - KEY entry_user_sort (entry_user_sort,entry_id)
  - KEY entry_category_sort(entry_category_sort,entry_id)
  - KEY entry_datetime_sort(entry_datetime,entry_id)
  - KEY entry_sub_category(entry_id,entry_status,entry_approval,entry_datetime,entry_start_datetime,entry_end_datetime,entry_indexing,entry_category_id,entry_blog_id)
%{PREFIX}entry_rev:
  - PRIMARY KEY  (entry_id,entry_start_datetime,entry_end_datetime,entry_status,entry_rev_id)
  - UNIQUE KEY entry_posted_datetime (entry_posted_datetime,entry_id,entry_rev_id)
  - KEY entry_code (entry_code,entry_category_id,entry_blog_id,entry_status)
  - KEY entry_status (entry_datetime,entry_start_datetime,entry_end_datetime,entry_status,entry_indexing,entry_id)
  - KEY entry_user_id (entry_user_id)
  - KEY entry_category_id (entry_category_id)
  - KEY entry_user_sort (entry_user_sort,entry_id)
  - KEY entry_category_sort(entry_category_sort,entry_id)
  - KEY entry_datetime_sort(entry_datetime,entry_id)
%{PREFIX}relationship:
  - PRIMARY KEY (relation_id,relation_eid,relation_type)
  - KEY relation_order (relation_id,relation_order)
%{PREFIX}relationship_rev:
  - PRIMARY KEY (relation_id,relation_eid,relation_rev_id,relation_type)
  - KEY relation_order (relation_id,relation_order,relation_rev_id)
%{PREFIX}field:
  - KEY field_cid (field_cid)
  - KEY field_uid (field_uid)
  - KEY field_bid (field_bid)
  - KEY field_mid (field_mid)
  - KEY field_eid (field_eid,field_key,field_search)
  - KEY field_key (field_key)
  - KEY field_key_value (field_key,field_value(64))
  - KEY field_cid_sort (field_cid,field_sort)
  - KEY field_eid_sort (field_eid,field_sort)
  - KEY field_bid_sort (field_bid,field_sort)
%{PREFIX}field_rev:
  - KEY field_cid (field_cid)
  - KEY field_uid (field_uid)
  - KEY field_bid (field_bid)
  - KEY field_mid (field_mid)
  - KEY field_eid (field_eid,field_key,field_search,field_rev_id)
  - KEY field_key (field_key)
  - KEY field_key_value (field_key,field_value(64))
  - KEY acms_field_cid_sort (field_cid,field_sort,field_rev_id)
  - KEY acms_field_eid_sort (field_eid,field_sort,field_rev_id)
  - KEY acms_field_bid_sort (field_bid,field_sort,field_rev_id)
%{PREFIX}form:
  - PRIMARY KEY  (form_id)
%{PREFIX}fulltext:
  - UNIQUE KEY fulltext_cid (fulltext_cid)
  - UNIQUE KEY fulltext_uid (fulltext_uid)
  - UNIQUE KEY fulltext_bid (fulltext_bid)
  - UNIQUE KEY fulltext_eid (fulltext_eid)
  - KEY fulltext_value (fulltext_value(255))
  - FULLTEXT KEY fulltext_ngram (fulltext_ngram)
%{PREFIX}geo:
  - KEY geo_eid (geo_eid)
  - KEY geo_bid (geo_bid)
  - KEY geo_cid (geo_cid)
  - KEY geo_uid (geo_uid)
  - SPATIAL KEY geo_geometry (geo_geometry)
%{PREFIX}geo_rev:
  - KEY geo_eid (geo_eid,geo_rev_id)
  - KEY geo_bid (geo_bid,geo_rev_id)
  - KEY geo_cid (geo_cid,geo_rev_id)
  - KEY geo_uid (geo_uid,geo_rev_id)
%{PREFIX}layout_grid:
  - KEY layout_grid_id (layout_grid_identifier)
  - KEY layout_grid (layout_grid_parent,layout_grid_col,layout_grid_row)
%{PREFIX}media_tag:
  - PRIMARY KEY  (media_tag_media_id,media_tag_sort)
  - KEY media_tag_name_media (media_tag_name,media_tag_media_id)
  - KEY media_tag_blog_id (media_tag_blog_id,media_tag_name)
%{PREFIX}media:
  - PRIMARY KEY  (media_id)
%{PREFIX}log_form:
  - KEY log_form_datetime (log_form_datetime)
  - KEY log_form_serial (log_form_serial)
%{PREFIX}audit_log:
  - PRIMARY KEY (audit_log_id)
  - KEY audit_log_index (audit_log_datetime,audit_log_level_name,audit_log_session_uid)
%{PREFIX}module:
  - PRIMARY KEY  (module_identifier,module_name,module_blog_id,module_scope)
%{PREFIX}role:
  - PRIMARY KEY  (role_id)
%{PREFIX}role_blog:
  - PRIMARY KEY  (role_id,blog_id)
%{PREFIX}rule:
  - KEY rule_sort (rule_sort,rule_blog_id)
  - KEY rule_blog_id (rule_blog_id,rule_status)
%{PREFIX}sequence_plugin:
  - PRIMARY KEY  (sequence_plugin_key)
%{PREFIX}sequence:
%{PREFIX}schedule:
  - KEY schedule_id (schedule_id, schedule_year, schedule_month, schedule_blog_id)
%{PREFIX}shop_address:
  - PRIMARY KEY (address_id)
  - KEY address_user_id (address_primary, address_user_id)
%{PREFIX}shop_cart:
  - UNIQUE KEY shop_cart (cart_session_id, cart_blog_id)
%{PREFIX}session_php:
  - PRIMARY KEY  (session_id)
  - KEY session_expire (session_expire)
%{PREFIX}tag:
  - PRIMARY KEY  (tag_entry_id,tag_sort)
  - KEY tag_name_entry (tag_name,tag_entry_id)
  - KEY tag_blog_id (tag_blog_id,tag_name)
%{PREFIX}tag_rev:
  - PRIMARY KEY  (tag_entry_id,tag_sort,tag_rev_id)
  - KEY tag_name_entry (tag_name,tag_entry_id,tag_rev_id)
  - KEY tag_blog_id (tag_blog_id,tag_name,tag_rev_id)
%{PREFIX}trackback:
  - PRIMARY KEY  (trackback_entry_id,trackback_id,trackback_status)
%{PREFIX}user:
  - PRIMARY KEY  (user_id)
%{PREFIX}user_session:
  - KEY user_session (user_session_uid,user_session_host,user_session_address)
%{PREFIX}usergroup:
  - PRIMARY KEY  (usergroup_id)
  - KEY usergroup_role_id (usergroup_role_id)
  - KEY usergroup_role (usergroup_id,usergroup_role_id)
%{PREFIX}usergroup_user:
  - PRIMARY KEY  (usergroup_id,user_id)
%{PREFIX}workflow:
  - KEY workflow (workflow_blog_id,workflow_category_id)
%{PREFIX}workflow_usergroup:
  - KEY workflow_usergroup (workflow_blog_id,workflow_category_id,workflow_sort)
%{PREFIX}preview_share:
  - KEY preview_share_token (preview_share_token, preview_share_expire)
%{PREFIX}entry_sub_category:
  - KEY entry_sub_category (entry_sub_category_eid, entry_sub_category_id, entry_sub_category_blog_id)
%{PREFIX}entry_sub_category_rev:
  - KEY entry_sub_category (entry_sub_category_eid, entry_sub_category_rev_id, entry_sub_category_id, entry_sub_category_blog_id)
%{PREFIX}lock:
  - KEY lock_key (lock_key, lock_datetime, lock_address)
%{PREFIX}lock_source:
  - KEY lock_source (lock_source_key, lock_source_datetime, lock_source_address)
%{PREFIX}webhook:
  - PRIMARY KEY (webhook_id)
  - KEY status_type_global_blog (webhook_status,webhook_type,webhook_scope,webhook_blog_id)
%{PREFIX}log_webhook:
  - KEY log_webhook_id (log_webhook_id)
  - KEY log_webhook_id_datetime (log_webhook_id, log_webhook_datetime)
%{PREFIX}token:
  - KEY token_index (token_key, token_type, token_expire)
